name: excel_plus
description: A fast, memory-efficient Dart library for reading, creating, and editing Excel (.xlsx) files.
version: 0.0.1
homepage: https://github.com/Masum-MSNR/excel_plus
repository: https://github.com/Masum-MSNR/excel_plus
issue_tracker: https://github.com/Masum-MSNR/excel_plus/issues
topics:
  - excel
  - xlsx
  - spreadsheet
  - office
  - dart

environment:
  sdk: ^3.11.4

dependencies:
  archive: ^4.0.4
  xml: ^6.3.0
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
